Repository PingCAP-QE/artifacts, pull requests merged in 2023-06, with the labels that each got.

#43 feat: add wget for tikv
  dockerfiles/tikv.Dockerfile
Labels: approved

#46 feat: tidb/tiflash add wget according to operator
  dockerfiles/bases/Makefile
  dockerfiles/bases/tidb-base/Dockerfile
  dockerfiles/bases/tiflash-base/Dockerfile
Labels: lgtm, approved, size/S

#47 chore: update tidb & tiflash base image to add wget
  dockerfiles/tidb.Dockerfile
  dockerfiles/tiflash.Dockerfile
Labels: lgtm, approved, size/XS

#49 feat(dockerfiles/ci-runtimes/base): Add java toolchain image
  dockerfiles/ci-runtimes/base/Dockerfile
Labels: lgtm, approved, size/M

#50 fix(dockerfiles/bases/pingcap-base): bump the base images to make more security
  dockerfiles/bases/pingcap-base/Dockerfile
Labels: lgtm, approved, size/XS

#51 chore: update product images to newer base image
  dockerfiles/bases/pd-base/Dockerfile
  dockerfiles/bases/tidb-base/Dockerfile
  dockerfiles/bases/tiflash-base/Dockerfile
  dockerfiles/bases/tikv-base/Dockerfile
  dockerfiles/bases/tools-base/Dockerfile
  dockerfiles/br.Dockerfile
  dockerfiles/dm.Dockerfile
  dockerfiles/dumpling.Dockerfile
  dockerfiles/ng-monitoring.Dockerfile
  dockerfiles/pd.Dockerfile
  dockerfiles/ticdc.Dockerfile
  dockerfiles/tidb-binlog.Dockerfile
  dockerfiles/tidb-enterprise.Dockerfile
  dockerfiles/tidb-lightning-debug.Dockerfile
  dockerfiles/tidb-lightning.Dockerfile
  dockerfiles/tidb-tools.Dockerfile
  dockerfiles/tidb.Dockerfile
  dockerfiles/tiflash.Dockerfile
  dockerfiles/tikv.Dockerfile
Labels: lgtm, approved, size/M
