Repository PingCAP-QE/artifacts, pull requests merged in 2023-08, with the labels that each got.

#64 update release base image
  dockerfiles/ci-runtimes/base/Dockerfile
  dockerfiles/ci-runtimes/release-build-base/Dockerfile
  dockerfiles/ci-runtimes/release-build-base/tiflash/Dockerfile
  dockerfiles/ci-runtimes/release.yaml
Labels: lgtm, approved, size/L

#65 fix(dockerfiles/ci-runtimes/base): fix ci base image dockerfile
  dockerfiles/ci-runtimes/base/Dockerfile
Labels: lgtm, approved, size/XS

#66 feat(config): add packages central declare configuration
  packages/README.md
  packages/offline-packages.yaml.tmpl
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/XXL

#71 feat: add re-recover and jq to pd
  dockerfiles-multi-stages/pd/Dockerfile
  dockerfiles/bases/pd-base/Dockerfile
  dockerfiles/pd.Dockerfile
Labels: lgtm, approved, size/S

#72 feat: migrate centos-stream from private docker repo
  dockerfiles/old-bases/arm64/centos-stream.Dockerfile
Labels: lgtm, approved, size/S

#73 chore(packages): update offline package config
  dockerfiles/ci-runtimes/release-build-base/Dockerfile
  packages/offline-packages.yaml.tmpl
Labels: lgtm, approved, size/L
