Repository PingCAP-QE/artifacts, pull requests merged in 2023-12, with the labels that each got.

#149 chore: bump base image verison
  dockerfiles/bases/skaffold.yaml
Labels: lgtm, approved, size/XS

#153 chore: bump base image
  dockerfiles/br.Dockerfile
  dockerfiles/dm.Dockerfile
  dockerfiles/dumpling.Dockerfile
  dockerfiles/ng-monitoring.Dockerfile
  dockerfiles/pd.Dockerfile
  dockerfiles/products/br.Dockerfile
  dockerfiles/products/dm.Dockerfile
  dockerfiles/products/dumpling.Dockerfile
  dockerfiles/products/ng-monitoring.Dockerfile
  dockerfiles/products/pd.Dockerfile
  dockerfiles/products/ticdc.Dockerfile
  dockerfiles/products/tidb-binlog.Dockerfile
  dockerfiles/products/tidb-enterprise.Dockerfile
  dockerfiles/products/tidb-lightning-debug.Dockerfile
  dockerfiles/products/tidb-lightning.Dockerfile
  dockerfiles/products/tidb-tools.Dockerfile
  dockerfiles/products/tidb.Dockerfile
  dockerfiles/products/tiflash.Dockerfile
  dockerfiles/products/tikv.Dockerfile
  dockerfiles/ticdc.Dockerfile
  dockerfiles/tidb-binlog.Dockerfile
  dockerfiles/tidb-enterprise.Dockerfile
  dockerfiles/tidb-lightning-debug.Dockerfile
  dockerfiles/tidb-lightning.Dockerfile
  dockerfiles/tidb-tools.Dockerfile
  dockerfiles/tidb.Dockerfile
  dockerfiles/tiflash.Dockerfile
  dockerfiles/tikv.Dockerfile
Labels: lgtm, approved, size/M

#154 feat(packages/scripts): output push results to files
  packages/scripts/build-package-artifacts.sh.tmpl
  packages/scripts/build-package-images.sh.tmpl
Labels: approved, size/L

#155 fix(pacakges): fix script template
  packages/scripts/build-package-artifacts.sh.tmpl
Labels: approved, size/XS

#156 fix(pacakges): fix script template for building images
  packages/scripts/build-package-images.sh.tmpl
Labels: approved, size/XS

#158 fix(packages/scripts): push more tags for OCI artifacts
  packages/scripts/build-package-artifacts.sh.tmpl
Labels: approved, size/XS

#157 feat: add fips config
  .github/workflows/pull-cd-builder-images.yaml
  .github/workflows/pull-cd-util-images.yaml
  .github/workflows/pull-ci-runtime-images.yaml
  .github/workflows/pull-prod-runtime-images.yaml
  .github/workflows/release-cd-builder-images.yaml
  .github/workflows/release-cd-util-images.yaml
  .github/workflows/release-ci-runtime-images.yaml
  .github/workflows/release-prod-runtime-images.yaml
  dockerfiles-multi-stages/dumpling/Dockerfile
  dockerfiles/bases/ng-monitoring-base/Dockerfile
  dockerfiles/bases/pd-base/Dockerfile
  dockerfiles/bases/pingcap-base/Dockerfile
  dockerfiles/bases/skaffold.yaml
  dockerfiles/bases/tidb-base/Dockerfile
  dockerfiles/bases/tiflash-base/Dockerfile
  dockerfiles/bases/tikv-base/Dockerfile
  dockerfiles/bases/tikv-base/fips.Dockerfile
  dockerfiles/bases/tools-base/Dockerfile
  dockerfiles/cd/builders/skaffold.yaml
  dockerfiles/cd/builders/tidb-dashboard/Dockerfile
  dockerfiles/cd/builders/tikv/fips.Dockerfile
  dockerfiles/products/tidb-dashboard.Dockerfile
  dockerfiles/products/tikv-fips.Dockerfile
  packages/packages.yaml.tmpl
Labels: approved, size/XL

#162 fix(packages): make tag ok for feature branches or ther tree style branches
  packages/packages.yaml.tmpl
  packages/scripts/build-package-artifacts.sh.tmpl
Labels: approved, size/M

#163 opt(packages): simple package configurations
  packages/offline-packages.yaml.tmpl
  packages/packages.yaml.tmpl
  packages/scripts/build-offline-package-with-config.sh
  packages/scripts/gen-package-artifacts-with-config.sh
  packages/scripts/gen-package-images-with-config.sh
Labels: approved, size/L

#165 fix(dockerfiles/cd/builders): fix multi stage dockerfile for tidb-dashboard
  dockerfiles/cd/builders/skaffold.yaml
  dockerfiles/cd/builders/tidb-dashboard/Dockerfile
  dockerfiles/cd/builders/tiflash/Dockerfile
Labels: approved, size/M

#167 ci: add job "Pull test for packages cfg"
  .github/workflows/pull-verify-packages-config.yaml
Labels: approved, size/M

#168 feat(tidb): add product base image
  .github/workflows/pull-prod-runtime-images.yaml
  .github/workflows/release-prod-runtime-images.yaml
  dockerfiles/bases/skaffold.yaml
  dockerfiles/bases/tidb-base/release-6.5.Dockerfile
  dockerfiles/products/tidb-enterprise-release-6.5.Dockerfile
  dockerfiles/products/tidb-release-6.5.Dockerfile
Labels: approved, size/M

#169 fix(packages): add tarball artifacts for pd on fips profile for v6.5.x
  packages/packages.yaml.tmpl
Labels: approved, size/S

#166 ci: split skaffold module for tiflash builder image
  .github/workflows/pull-cd-builder-images.yaml
  .github/workflows/pull-verify-packages-config.yaml
  .github/workflows/release-cd-builder-images.yaml
  .github/workflows/release-cd-util-images.yaml
  .github/workflows/release-ci-runtime-images.yaml
  .github/workflows/release-prod-runtime-images.yaml
  dockerfiles/cd/builders/skaffold.yaml
  dockerfiles/cd/utils/skaffold.yaml
  dockerfiles/ci/skaffold.yaml
Labels: approved, size/L

#170 feat: add tiup tarball artifact for fips
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/M

#172 feat(dockerfiles/cd): add builder image for tidb-dashboard
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/M

#178 docs(packages): Update README.md
  .github/workflows/pull-verify-packages-config.yaml
  packages/README.md
  packages/offline-packages.yaml.tmpl
  packages/packages.yaml.tmpl
  packages/scripts/get-package-builder-with-config.sh
Labels: size/L

#180 refactor(packages): increase readability of package.yaml.tmpl
  .github/workflows/pull-verify-packages-config.yaml
  packages/packages.yaml.tmpl
  packages/scripts/build-package-artifacts.sh.tmpl
  packages/scripts/gen-package-artifacts-with-config.sh
  packages/scripts/gen-package-images-with-config.sh
Labels: approved, size/XL

#181 refactor(packages): split builder from routers
  .github/workflows/pull-verify-packages-config.yaml
  packages/README.md
  packages/packages.yaml.tmpl
  packages/scripts/ci.sh
  packages/scripts/gen-package-artifacts-with-config.sh
  packages/scripts/gen-package-images-with-config.sh
  packages/scripts/get-package-builder-with-config.sh
Labels: approved, size/XL

#184 feat(packges): add tiproxy into configuration
  dockerfiles/products/tiproxy/Dockerfile
  packages/packages.yaml.tmpl
  packages/scripts/ci.sh
Labels: lgtm, approved, size/XXL

#185 feat(packages/scripts): add checksum(sha256) for files in OCI
  packages/scripts/build-package-artifacts.sh.tmpl
Labels: lgtm, approved, size/XS

#186 feat(packages): add meta data into the OCI artifacts
  packages/packages.yaml.tmpl
  packages/scripts/build-package-artifacts.sh.tmpl
  packages/scripts/gen-package-artifacts-with-config.sh
Labels: lgtm, approved, size/M

#187 feat(packages): support enterprise build profile for tidb
  packages/README.md
  packages/packages.yaml.tmpl
  packages/scripts/build-package-artifacts.sh.tmpl
  packages/scripts/build-package-images.sh.tmpl
  packages/scripts/ci.sh
Labels: approved, size/L

#190 fix(packages): add tiup metadata for cdc
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#189 feat(packages): add offline pkg scripts
  packages/offline-packages.yaml.tmpl
  packages/scripts/build-offline-package-with-config.sh
  packages/scripts/ci.sh
  packages/scripts/compose-offline-packages-artifact.sh.tmpl
  packages/scripts/compose-offline-packages-artifacts.sh.tmpl
  packages/scripts/gen-package-offline-package-with-config.sh
Labels: approved, size/XL
