Repository PingCAP-QE/artifacts, pull requests merged in 2023-07, with the labels that each got.

#55 chore: update go version to 1.20
  dockerfiles-multi-stages/dm/Dockerfile
  dockerfiles-multi-stages/pd/Dockerfile
  dockerfiles-multi-stages/ticdc/Dockerfile
  dockerfiles-multi-stages/tidb/Dockerfile
Labels: lgtm, approved, size/XS

#58 fix(dockerfiles/ci-runtimes/base): fix codecov binary fetching for arm64 image
  dockerfiles/ci-runtimes/base/Dockerfile
Labels: lgtm, approved, size/S

#59 fix(dockerfiles/ci-runtimes): add release-build-base image
  dockerfiles/ci-runtimes/base/Dockerfile
  dockerfiles/ci-runtimes/release-build-base/Dockerfile
  dockerfiles/ci-runtimes/release-build-base/tikv/Dockerfile
  dockerfiles/ci-runtimes/release.yaml
Labels: lgtm, approved, size/L

#61 Update tidb multi-stages Dockerfile
  dockerfiles-multi-stages/tidb/Dockerfile
Labels: lgtm, approved
