Repository PingCAP-QE/artifacts, pull requests merged in 2023-11, with the labels that each got.

#105 feat(packges): add packaging scripts
  packages/packages.yaml.tmpl
  packages/scripts/build-offline-package-with-config.sh
  packages/scripts/build-package-artifacts-with-config.sh
  packages/scripts/build-package-artifacts.sh.tmpl
  packages/scripts/build-package-images-with-config.sh
  packages/scripts/build-package-images.sh.tmpl
  packages/scripts/compose-offline-packages-artifact.sh.tmpl
Labels: approved, size/XL

#106 feat(packges): add packaging scripts (#105)
  packages/scripts/build-package-images-with-config.sh
Labels: approved, size/XS

#107 feat(dockerfiles/ci): add release utils image
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .gitignore
  Justfile
  dockerfiles/bases/Makefile
  dockerfiles/bases/pd-base/Dockerfile
  dockerfiles/bases/skaffold.yaml
  dockerfiles/bases/tidb-base/Dockerfile
  dockerfiles/bases/tiflash-base/Dockerfile
  dockerfiles/bases/tikv-base/Dockerfile
  dockerfiles/bases/tools-base/Dockerfile
  dockerfiles/ci/base/Dockerfile
  dockerfiles/ci/release-build-base/Dockerfile
  dockerfiles/ci/release-build-base/tiflash/Dockerfile
  dockerfiles/ci/release-utils/Dockerfile
  dockerfiles/ci/skaffold.yaml
  dockerfiles/ee-apps/ats/Dockerfile
Labels: approved, size/XXL

#108 feat(dockerfiles/ci): add bash tool to release utils image
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  Justfile
  dockerfiles/ci/release-utils/Dockerfile
Labels: size/S

#109 chore: update etcd version
  packages/offline-packages.yaml.tmpl
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/S

#110 chore: remove tispark and spark since v7.5
  packages/offline-packages.yaml.tmpl
Labels: lgtm, approved, size/XS

#111 refactor(dockerfiles,dockerfiles-multi-stages): simple builder image for pd
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  README.md
  dockerfiles-multi-stages/pd/Dockerfile
  dockerfiles/bases/skaffold.yaml
  dockerfiles/cd/README.md
  dockerfiles/cd/tikv/pd/Dockerfile
Labels: lgtm, approved, size/XL

#113 ci: fix release github workflow
  .github/workflows/release.yaml
Labels: approved, size/XS

#112 feat: add perl to pd base image
  dockerfiles/bases/pd-base/Dockerfile
Labels: lgtm, approved, size/XS

#115 ci: fix github ci and release flows
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
Labels: approved, size/S

#116 feat: add perl to ng-monitoring
  dockerfiles/bases/ng-monitoring-base/Dockerfile
  dockerfiles/bases/skaffold.yaml
  dockerfiles/ng-monitoring.Dockerfile
Labels: lgtm, approved, size/S

#118 refactor(dockerfiles/cd): refactor multi stages building dockerfiles for tiflow
  Justfile
  dockerfiles-multi-stages/dm/Dockerfile
  dockerfiles-multi-stages/ticdc/Dockerfile
  dockerfiles/cd/pingcap/tiflow/Dockerfile
  dockerfiles/cd/tikv/pd/Dockerfile
  packages/packages.yaml.tmpl
Labels: approved, size/L

#119 fix(packages): fix packages.yaml.tmpl
  Justfile
  dockerfiles/cd/tikv/pd/Dockerfile
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#121 refactor(dockerfiles/cd/pingcap/tidb): update it to real CD's builder and building stages
  Justfile
  dockerfiles-multi-stages/tidb/Dockerfile
  dockerfiles/cd/pingcap/tidb/Dockerfile
Labels: approved, size/M

#122 ci: split CI pull jobs
  .github/workflows/ci.yaml
  .github/workflows/pull-cd-build-base-images.yaml
  .github/workflows/pull-ci-release-utils-images.yaml
  .github/workflows/pull-ci-runtime-base-images.yaml
  .github/workflows/pull-prod-runtime-base-images.yaml
  Justfile
  dockerfiles-multi-stages/tikv/Dockerfile
  dockerfiles/cd/pingcap/tiflash/Dockerfile
  dockerfiles/cd/skaffold.yaml
  dockerfiles/cd/tikv/tikv/Dockerfile
  dockerfiles/ci/release-build-base/tiflash/Dockerfile
Labels: approved, size/XXL

#123 ci: refactor CI/CD flows for images
  .github/workflows/pull-cd-builder-images.yaml
  .github/workflows/pull-ci-runtime-images.yaml
  .github/workflows/pull-prod-runtime-images.yaml
  .github/workflows/release-cd-builder-images.yaml
  .github/workflows/release-ci-runtime-images.yaml
  .github/workflows/release-prod-runtime-images.yaml
  .github/workflows/release.yaml
Labels: approved, size/XL

#130 feat(packages): update packages.yaml.tmpl
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/M

#131 fix(packges): fix package names and push destinations
  packages/packages.yaml.tmpl
  packages/scripts/build-package-artifacts.sh.tmpl
Labels: approved, size/M

#132 fix(packges): add mac build targets for tiflow
  packages/packages.yaml.tmpl
  packages/scripts/build-package-artifacts.sh.tmpl
  packages/scripts/build-package-images.sh.tmpl
Labels: approved, size/M

#133 feat(packages): update packages.yaml.tmpl
  packages/packages.yaml.tmpl
Labels: approved, size/S

#134 fix(dockerfiles): fix skaffold.yaml
  dockerfiles/cd/skaffold.yaml
  dockerfiles/ci/skaffold.yaml
Labels: size/M

#136 feat(packages): add dvanced-statefulset to packages configuration
  packages/packages.yaml.tmpl
  packages/scripts/build-package-images.sh.tmpl
Labels: approved, size/M

#138 chore(packages): add arm64 image targets for `pingcap/advance-statefulset`
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#140 fix(packages): use the latest gommplate function
  packages/offline-packages.yaml.tmpl
  packages/packages.yaml.tmpl
Labels: approved, size/M

#142 refactor(dockerfiles/cd): new a builders dir to split with cd/utils
  .github/workflows/pull-cd-builder-images.yaml
  .github/workflows/release-cd-builder-images.yaml
  Justfile
  dockerfiles/cd/README.md
  dockerfiles/cd/builders/pd/Dockerfile
  dockerfiles/cd/builders/skaffold.yaml
  dockerfiles/cd/builders/tidb/Dockerfile
  dockerfiles/cd/builders/tiflash/Dockerfile
  dockerfiles/cd/builders/tiflow/Dockerfile
  dockerfiles/cd/builders/tikv/Dockerfile
Labels: approved, size/M
