Repository PingCAP-QE/artifacts, pull requests merged in 2023-10, with the labels that each got.

#77 chore(packages): update release configs
  packages/offline-packages.yaml.tmpl
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/XXL

#78 fix: base image security
  dockerfiles/bases/Makefile
  dockerfiles/bases/pd-base/Dockerfile
  dockerfiles/bases/pingcap-base/Dockerfile
  dockerfiles/bases/tidb-base/Dockerfile
  dockerfiles/bases/tiflash-base/Dockerfile
  dockerfiles/bases/tikv-base/Dockerfile
  dockerfiles/bases/tools-base/Dockerfile
Labels: lgtm, approved, size/M

#79 fix: base image security
  dockerfiles/br.Dockerfile
  dockerfiles/dm.Dockerfile
  dockerfiles/dumpling.Dockerfile
  dockerfiles/ng-monitoring.Dockerfile
  dockerfiles/pd.Dockerfile
  dockerfiles/ticdc.Dockerfile
  dockerfiles/tidb-binlog.Dockerfile
  dockerfiles/tidb-enterprise.Dockerfile
  dockerfiles/tidb-lightning-debug.Dockerfile
  dockerfiles/tidb-lightning.Dockerfile
  dockerfiles/tidb-tools.Dockerfile
  dockerfiles/tidb.Dockerfile
  dockerfiles/tiflash.Dockerfile
  dockerfiles/tikv.Dockerfile
Labels: lgtm, approved, size/S

#83 ci(dockerfiles/ci-runtimes): fix skaffold config
  .github/renovate.json
  dockerfiles/bases/pingcap-base/Dockerfile
  dockerfiles/bases/skaffold.yaml
  dockerfiles/ci-runtimes/skaffold.yaml
  renovate.json
Labels: lgtm, approved, size/XL

#85 feat: remove mydumper and tikv-importer for v7.5
  packages/offline-packages.yaml.tmpl
Labels: lgtm, approved, size/L

#86 Action Required: Fix Renovate Configuration
  .github/renovate.json
Labels: approved, size/XS

#89 Build base images automaticly
  .github/workflows/ci.yaml
  dockerfiles/bases/skaffold.yaml
  dockerfiles/ci-runtimes/skaffold.yaml
Labels: approved, size/L

#93 ci: fix skaffold version
  .github/workflows/ci.yaml
Labels: approved, size/XS

#94 ci: fix skaffold config
  .github/workflows/ci.yaml
  dockerfiles/bases/skaffold.yaml
  dockerfiles/ci/base/Dockerfile
  dockerfiles/ci/release-build-base/Dockerfile
  dockerfiles/ci/release-build-base/tiflash/Dockerfile
  dockerfiles/ci/release-build-base/tikv/Dockerfile
  dockerfiles/ci/skaffold.yaml
Labels: approved, size/M

#97 chore(dockerfiles): bump oras to v1.1.0
  dockerfiles/ci/base/Dockerfile
  dockerfiles/ci/release-build-base/Dockerfile
Labels: approved, size/S

#101 ci: add concurrent limit
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
Labels: approved, size/S
