Repository PingCAP-QE/artifacts, pull requests merged in 2024-03, with the labels that each got.

#258 refactor(pingcap/ng-monitoring,pingcap/monitoring): drive the "prometheus" tiup pkg building from `pingcap/monitoring`
  packages/packages.yaml.tmpl
  packages/scripts/ci.sh
Labels: lgtm, approved, size/XL

#260 fix(packages): add enterprise profiles
  packages/packages.yaml.tmpl
  packages/scripts/ci.sh
Labels: lgtm, approved, size/M

#261 fix(pingcap/monitoring): fix builders
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#262 feat(pingcap/monitoring): support build for tag creating triggers
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#264 fix(packages): rename profile `debug` to `failpoint`
  packages/README.md
  packages/packages.yaml.tmpl
  packages/scripts/ci.sh
Labels: approved, size/S

#265 fix(packages): bump etcdctl to v3.4.30
  packages/offline-packages.yaml.tmpl
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/S

#266 Update packages.yaml.tmpl
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#267 Revert "Update packages.yaml.tmpl"
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#268 feat(packages): add tag for OCI artifacts with release version
  packages/packages.yaml.tmpl
Labels: approved, size/S

#271 feat(packages/scripts): support check before composing offline packages
  packages/scripts/compose-offline-packages-artifacts.sh.tmpl
  packages/scripts/gen-package-offline-package-with-config.sh
Labels: approved, size/L

#272 feat: add pcc and dba to all platform
  packages/offline-packages.yaml.tmpl
Labels: lgtm, approved, size/S

#273 fix(pingcap/ng-monitoring): fix image building
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#269 feat: support sync enterprise image
  packages/delivery.yaml
  packages/scripts/gen-delivery-image-commands.ts
Labels: approved, size/M

#274 feat(packages/scripts): add label for oci artifacts and iamges
  packages/scripts/build-package-artifacts.sh.tmpl
  packages/scripts/build-package-images.sh.tmpl
  packages/scripts/compose-offline-packages-artifacts.sh.tmpl
Labels: approved, size/S

#275 feat(packages/scripts): add more tags for image
  packages/scripts/build-package-images.sh.tmpl
Labels: approved, size/M

#277 fix(packages/scripts): fix image add tags function
  packages/scripts/build-package-artifacts.sh.tmpl
  packages/scripts/build-package-images.sh.tmpl
Labels: approved, size/XS

#279 feat: sync RC enterprise image to gcr
  packages/delivery.yaml
Labels: lgtm, approved, size/S

#278 fix(package/scripts): fix taging for artifacts
  packages/scripts/build-package-artifacts.sh.tmpl
  packages/scripts/build-package-images.sh.tmpl
  packages/scripts/compose-offline-packages-artifacts.sh.tmpl
Labels: approved, size/M

#281 fix: typo dbaas
  packages/delivery.yaml
Labels: lgtm, approved, size/S

#282 fix: sync failpoint image to qa
  packages/delivery.yaml
Labels: lgtm, approved, size/XS

#283 fix(package): tidb-ctl only has master branch
  packages/packages.yaml.tmpl
Labels: size/XS

#287 fix(tikv/pd): try to fix pd's failpoint
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#288 fix(packages): fix tidb-binlog image context config
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/XS

#286 feat(package): support enterprise tiup offline deploy packages
  packages/offline-packages.yaml.tmpl
  packages/scripts/compose-offline-packages-artifacts.sh.tmpl
  packages/scripts/gen-package-offline-package-with-config.sh
Labels: approved, size/XL

#289 feat(packages/scripts): add pre to ga script
  packages/offline-packages.yaml.tmpl
  packages/scripts/compose-offline-packages-artifacts.sh.tmpl
  packages/scripts/pre-to-ga-tag.sh
Labels: approved, size/M

#290 opt(packages): abstract the delivery tag regexes
  packages/delivery.yaml
  packages/scripts/pre-to-ga-tag.sh
Labels: approved, size/L

#293 opt(packages): add retry for http fetching
  packages/scripts/build-package-artifacts.sh.tmpl
  packages/scripts/build-package-images.sh.tmpl
  packages/scripts/compose-offline-packages-artifacts.sh.tmpl
Labels: approved, size/XS

#294 fix(packges): fix offline-package config
  packages/offline-packages.yaml.tmpl
Labels: approved, size/XS

#295 fix(packges): hotfix offline-package config for v8.0.0
  packages/offline-packages.yaml.tmpl
Labels: approved, size/S

#297 feat(packages): add image copy rule for `advanced-statefulset`
  packages/delivery.yaml
Labels: lgtm, approved, size/XS
