Repository PingCAP-QE/artifacts, pull requests merged in 2024-11, with the labels that each got.

#479 feat: add tools mariadb client 5.5.68
  dockerfiles/ci/base/Dockerfile
Labels: lgtm, approved, size/S

#469 refactor(dockerfile): update dockerfile for release 6.5
  .github/scripts/ci.sh
  dockerfiles/products/le6.5-linux-amd64-debug/tiem
  dockerfiles/products/le6.5-linux-amd64/tiem
  dockerfiles/products/le6.5-linux-arm64/dm-monitor-initializer
  dockerfiles/products/le6.5-linux-arm64/tidb-operator
  dockerfiles/products/ng-monitoring/Dockerfile
  dockerfiles/products/ng-monitoring/lt6.5.12/Dockerfile
  dockerfiles/products/ng-monitoring/~6.5.12/Dockerfile
  dockerfiles/products/pd/Dockerfile
  dockerfiles/products/pd/lt6.5.12/Dockerfile
  dockerfiles/products/pd/~6.5.12/Dockerfile
  dockerfiles/products/tidb-binlog/Dockerfile
  dockerfiles/products/tidb-binlog/lt6.5.12/Dockerfile
  dockerfiles/products/tidb-binlog/~6.5.12/Dockerfile
  dockerfiles/products/tidb-dashboard/Dockerfile
  dockerfiles/products/tidb-dashboard/lt6.5.12/Dockerfile
  dockerfiles/products/tidb-dashboard/~6.5.12/Dockerfile
  dockerfiles/products/tidb-tools/Dockerfile
  dockerfiles/products/tidb-tools/lt6.5.12/Dockerfile
  dockerfiles/products/tidb-tools/~6.5.12/Dockerfile
  dockerfiles/products/tidb.enterprise.Dockerfile
  dockerfiles/products/tidb/br.Dockerfile
  dockerfiles/products/tidb/dumpling.Dockerfile
  dockerfiles/products/tidb/lt6.5.12/br.Dockerfile
  dockerfiles/products/tidb/lt6.5.12/dumpling.Dockerfile
  dockerfiles/products/tidb/lt6.5.12/tidb-lightning.Dockerfile
  dockerfiles/products/tidb/lt6.5.12/tidb.Dockerfile
  dockerfiles/products/tidb/lt6.5.12/tidb.enterprise.Dockerfile
  dockerfiles/products/tidb/tidb-lightning.Dockerfile
  dockerfiles/products/tidb/tidb.Dockerfile
  dockerfiles/products/tidb/tidb.enterprise.Dockerfile
  dockerfiles/products/tidb/~6.5.12/br.Dockerfile
  dockerfiles/products/tidb/~6.5.12/dumpling.Dockerfile
  dockerfiles/products/tidb/~6.5.12/tidb-lightning.Dockerfile
  dockerfiles/products/tidb/~6.5.12/tidb.Dockerfile
  dockerfiles/products/tidb/~6.5.12/tidb.enterprise.Dockerfile
  dockerfiles/products/tiflash/Dockerfile
  dockerfiles/products/tiflash/lt6.5.12/Dockerfile
  dockerfiles/products/tiflash/~6.5.12/Dockerfile
  dockerfiles/products/tiflow/dm.Dockerfile
  dockerfiles/products/tiflow/lt6.5.12/dm.Dockerfile
  dockerfiles/products/tiflow/lt6.5.12/ticdc.Dockerfile
  dockerfiles/products/tiflow/ticdc.Dockerfile
  dockerfiles/products/tiflow/~6.5.12/dm.Dockerfile
  dockerfiles/products/tiflow/~6.5.12/ticdc.Dockerfile
  dockerfiles/products/tikv/Dockerfile
  dockerfiles/products/tikv/fips.Dockerfile
  dockerfiles/products/tikv/lt6.5.12/Dockerfile
  dockerfiles/products/tikv/~6.5.12/Dockerfile
  packages/packages.yaml.tmpl
Labels: approved, size/XL

#481 fix(packages): update builder image tags
  packages/packages.yaml.tmpl
Labels: approved, size/M

#482 fix(dockerfiles/cd/builders/tiflash): update llvm installation steps
  dockerfiles/cd/builders/tiflash/Dockerfile
Labels: size/M

#487 fix(pingcap/tiflash): fix builder image
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#488 chore(tiflash): update build steps for tiflash starts v8.5.0
  dockerfiles/cd/builders/tiflash/Dockerfile
  dockerfiles/cd/builders/tiflash/centos7/Dockerfile
  packages/packages.yaml.tmpl
Labels: approved, size/M

#484 feat(dockerfiles/cd/builders/tiflash): update image docker file for new tiflash builder
  dockerfiles/cd/builders/tiflash/Dockerfile
  dockerfiles/cd/builders/tiflash/centos7/Dockerfile
Labels: approved, size/L, ok-to-test

#491 chore(deps): bump golang version from 1.23.2 to 1.23.3
  dockerfiles/cd/builders/ng-monitoring/centos7/Dockerfile
  dockerfiles/cd/builders/pd/centos7/Dockerfile
  dockerfiles/cd/utils/release/Dockerfile
  dockerfiles/ci/release-build-base/Dockerfile
  packages/packages.yaml.tmpl
Labels: approved, size/S

#496 fix(dockerfiles/product/tidb): fix product docker file for patch version ~v6.5.12
  dockerfiles/products/tidb/~6.5.12/tidb.Dockerfile
Labels: approved, size/XS
