Repository PingCAP-QE/artifacts, pull requests merged in 2024-12, with the labels that each got.

#502 feat: ci image add mysql 5.7
  dockerfiles/ci/base/Dockerfile
  dockerfiles/ci/jenkins/tikv/Dockerfile
Labels: lgtm, approved, size/M

#512 chore(scripts): update scripts and delete useless files
  packages/scripts/gen-delivery-image-commands.ts
  packages/scripts/gen-delivery-images-with-config.sh
Labels: approved, size/M

#513 fix(packages): compatible with centos7 devtoolset build toolchain
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#515 feat(packages/scripts): add get-delivery-target-images.ts
  packages/scripts/get-delivery-target-images.ts
Labels: approved, size/L
