Repository PingCAP-QE/artifacts, pull requests merged in 2024-02, with the labels that each got.

#230 feat(packages): add image copy rules
  packages/delivery.yaml
Labels: approved, size/S

#231 feat(packages): add image copy scripts
  packages/delivery.yaml
  packages/scripts/gen-delivery-image-commands.ts
  packages/scripts/gen-delivery-images-with-config.sh
Labels: approved, size/L

#232 chore(deps): add golang builders for 1.18.x
  dockerfiles/cd/builders/skaffold.yaml
Labels: approved, size/S

#233 feat(packages): add image delivery rules
  packages/delivery.yaml
Labels: lgtm, approved, size/L

#234 fix(packages): fix src image repo
  packages/delivery.yaml
Labels: lgtm, approved, size/XS

#236 feat: add tidb-ctl config
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/S

#240 chore(pacakges): upgrade prometheus version to v2.49.1
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/M

#241 fix(dockerfiles/cd/utils/release): add uuidgen tool
  dockerfiles/cd/utils/release/Dockerfile
Labels: approved, size/XS

#243 ci(renovate): split the patch and minor updating
  .github/renovate.json
Labels: approved, size/S

#242 feat(dockerfiles/cd/builders): add builder image with go 1.22.x
  dockerfiles/cd/builders/pd/Dockerfile
  dockerfiles/cd/builders/skaffold.yaml
  dockerfiles/ci/skaffold.yaml
Labels: approved, size/S

#249 chore(pacakges): add json schema for delivery.yaml
  packages/delivery-schema.json
Labels: approved, size/M

#251 fix(pacakges): bump release util image to `v20231216-81-g3fc5aaa`
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#252 fix(pacakges): update the downloading url for etcd binary
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#253 fix(pacakges): delete git clone step in steps
  packages/packages.yaml.tmpl
Labels: approved, size/S

#256 fix(pingcap/ng-monitoring): fix rule file paths
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/S

#257 fix(pingcap/ng-monitoring): update packages.yaml.tmpl
  packages/packages.yaml.tmpl
Labels: approved, size/XS
