Repository PingCAP-QE/artifacts, pull requests merged in 2024-01, with the labels that each got.

#191 feat(dockerfiles/cd/utils): add ks3util image and update release util image
  dockerfiles/cd/utils/ks3util/Dockerfile
  dockerfiles/cd/utils/release/Dockerfile
  dockerfiles/cd/utils/skaffold.yaml
Labels: approved, size/S

#192 feat: add monitoring image
  packages/packages.yaml.tmpl
  packages/scripts/ci.sh
Labels: lgtm, approved, size/M

#193 fix(pcakges): fix packages.yaml.tmpl for tiflow on v6.5.x versions
  packages/packages.yaml.tmpl
Labels: approved, size/S

#194 fix(pcakges): fix packages.yaml.tmpl for tidb-operator on fips profile
  packages/packages.yaml.tmpl
  packages/scripts/gen-package-artifacts-with-config.sh
  packages/scripts/gen-package-images-with-config.sh
  packages/scripts/gen-package-offline-package-with-config.sh
Labels: approved, size/S

#196 Update release-6.5.Dockerfile
  dockerfiles/bases/tidb-base/release-6.5.Dockerfile
Labels: approved, size/XS

#195 fix(packages): fix config for `tidb-binlog` and `tidb-tools`
  packages/offline-packages.yaml.tmpl
  packages/packages.yaml.tmpl
  packages/scripts/ci.sh
Labels: approved, size/M

#198 feat: add prometheus build config
  .gitignore
  packages/README.md
  packages/packages.yaml.tmpl
  packages/scripts/build-package-artifacts.sh.tmpl
  packages/scripts/build-package-images.sh.tmpl
  packages/scripts/ci.sh
Labels: lgtm, approved, size/L

#200 fix(packages): fix configuration for offline packages
  packages/offline-packages.yaml.tmpl
  packages/scripts/build-package-artifacts.sh.tmpl
  packages/scripts/build-package-images.sh.tmpl
  packages/scripts/gen-package-offline-package-with-config.sh
Labels: approved, size/M

#201 fix: prometheus path
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/S

#204 fix(packages): fix builders for `tidb-tools`
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#206 fix(packages): fix builder for tidb-tools
  packages/packages.yaml.tmpl
Labels: approved, size/S

#205 feat: support grafana
  packages/packages.yaml.tmpl
  packages/scripts/build-package-artifacts.sh.tmpl
Labels: approved, size/M

#209 fix: add target branch env var
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/XS

#210 feat: build grafana without pull
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/XS

#211 feat: use simple golang builder for monitor
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/XS

#213 Update Dockerfile
  dockerfiles/cd/utils/remote/Dockerfile
Labels: approved, size/XS

#215 fix: add wget for ng-monitoring builder
  dockerfiles/cd/builders/ng-monitoring/Dockerfile
Labels: size/XS

#216 chore: update ng-monitoring builder image
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/XS

#217 perf(packages/scripts): improve efficiently of fetching file from artifacts
  packages/scripts/build-package-artifacts.sh.tmpl
  packages/scripts/build-package-images.sh.tmpl
  packages/scripts/compose-offline-packages-artifacts.sh.tmpl
Labels: approved, size/M

#219 feat: add tiflow-engine docker image
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/XS

#220 Revert "feat: add tiflow-engine docker image"
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#222 feat: add tiflow engine image artifact
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/XS

#223 fix(packages): some fix for file sources
  packages/packages.yaml.tmpl
Labels: approved, size/S

#224 fix build-package-images.sh.tmpl
  packages/scripts/build-package-images.sh.tmpl
Labels: lgtm, approved, size/XS

#225 Revert "fix build-package-images.sh.tmpl"
  packages/scripts/build-package-images.sh.tmpl
Labels: approved, size/XS

#227 fix: tiflow-operator builder
  packages/packages.yaml.tmpl
  packages/scripts/ci.sh
Labels: lgtm, approved, size/M
