Repository PingCAP-QE/artifacts, pull requests merged in 2024-06, with the labels that each got.

#325 feat(dockerfiles/cd/builders/tikv): add builder image with devtoolset 10
  .github/workflows/pull-cd-builder-images.yaml
  .github/workflows/release-cd-builder-images.yaml
  dockerfiles/cd/builders/skaffold.yaml
Labels: approved, size/S

#327 fix: update git version to fix security issue
  dockerfiles/ci/base/Dockerfile
Labels: lgtm, approved, size/S

#328 fix: update git version to fix security issue
  dockerfiles/ci/release-build-base/Dockerfile
Labels: lgtm, approved, size/S

#330 fix(dockerfiles/products): bump base image from v1.8.0 to v1.9.0
  dockerfiles/br.Dockerfile
  dockerfiles/dm.Dockerfile
  dockerfiles/dumpling.Dockerfile
  dockerfiles/ng-monitoring.Dockerfile
  dockerfiles/pd.Dockerfile
  dockerfiles/products/br.Dockerfile
  dockerfiles/products/dm.Dockerfile
  dockerfiles/products/dumpling.Dockerfile
  dockerfiles/products/ng-monitoring.Dockerfile
  dockerfiles/products/pd.Dockerfile
  dockerfiles/products/ticdc.Dockerfile
  dockerfiles/products/tidb-binlog.Dockerfile
  dockerfiles/products/tidb-dashboard.Dockerfile
  dockerfiles/products/tidb-enterprise-release-6.5.Dockerfile
  dockerfiles/products/tidb-enterprise.Dockerfile
  dockerfiles/products/tidb-lightning-debug.Dockerfile
  dockerfiles/products/tidb-lightning.Dockerfile
  dockerfiles/products/tidb-release-6.5.Dockerfile
  dockerfiles/products/tidb-tools.Dockerfile
  dockerfiles/products/tidb.Dockerfile
  dockerfiles/products/tiflash.Dockerfile
  dockerfiles/products/tikv-fips.Dockerfile
  dockerfiles/products/tikv.Dockerfile
  dockerfiles/products/tiproxy/Dockerfile
  dockerfiles/ticdc.Dockerfile
  dockerfiles/tidb-binlog.Dockerfile
  dockerfiles/tidb-enterprise.Dockerfile
  dockerfiles/tidb-lightning-debug.Dockerfile
  dockerfiles/tidb-lightning.Dockerfile
  dockerfiles/tidb-tools.Dockerfile
  dockerfiles/tidb.Dockerfile
  dockerfiles/tiflash.Dockerfile
  dockerfiles/tikv.Dockerfile
Labels: approved, size/L

#331 feat: tiflash use llvm17 to build on version >= 8.2
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/XS

#329 chore: auto bump git version by renovate
  dockerfiles/ci/base/Dockerfile
  dockerfiles/ci/release-build-base/Dockerfile
Labels: help wanted, lgtm, approved, size/XS
