Repository PingCAP-QE/artifacts, pull requests merged in 2024-10, with the labels that each got.

#452 feat(packages): switch to new builder for `release` profile
  .github/scripts/ci.sh
  packages/packages.yaml.tmpl
Labels: approved, size/XL

#458 fix(dockerfiles/ci/jenkins): set `USE_BAZEL_VERSION` env var to fixate the bazel version
  dockerfiles/ci/jenkins/Dockerfile
Labels: approved, size/XS

#457 fix(dockerfiles/cd/builders): install findutils package in builder
  dockerfiles/cd/builders/pd/Dockerfile
  dockerfiles/cd/builders/tidb/Dockerfile
Labels: approved, size/XS

#461 fix(packages): update builder config with new images
  packages/packages.yaml.tmpl
Labels: approved, size/S

#462 ci: fix builder image tags and simpfy the skaffold config
  .github/workflows/pull-cd-builder-images-centos7.yaml
  .github/workflows/pull-cd-util-images.yaml
  .github/workflows/pull-ci-runtime-images.yaml
  .github/workflows/pull-prod-runtime-images.yaml
  .github/workflows/release-cd-builder-images-centos7.yaml
  .github/workflows/release-cd-util-images.yaml
  .github/workflows/release-ci-runtime-images.yaml
  .github/workflows/release-prod-runtime-images.yaml
  Justfile
  dockerfiles/bases/skaffold.yaml
  dockerfiles/cd/builders/skaffold-centos7.yaml
  dockerfiles/cd/builders/skaffold.yaml
  dockerfiles/cd/utils/skaffold.yaml
  dockerfiles/ci/skaffold.yaml
Labels: approved, size/L

#465 chore: support build image for ci/jenkins dockerfile
  .github/workflows/release-ci-runtime-images.yaml
Labels: lgtm, approved, size/XS

#466 feat: add gh-ost tool to ci image
  dockerfiles/ci/base/Dockerfile
Labels: lgtm, approved, size/S

#468 fix(packages): fix builder for tidb-operator
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#467 feat: add diff ci jenkins image
  .github/workflows/pull-ci-runtime-images.yaml
  .github/workflows/release-ci-runtime-images.yaml
  dockerfiles/ci/base/Dockerfile
  dockerfiles/ci/jenkins/tiflash/Dockerfile
  dockerfiles/ci/jenkins/tikv/Dockerfile
  dockerfiles/ci/skaffold.yaml
Labels: lgtm, approved, size/L

#472 feat: add tools wget&hostname&free to tikv&tiflash ci images
  dockerfiles/ci/jenkins/tiflash/Dockerfile
  dockerfiles/ci/jenkins/tikv/Dockerfile
Labels: lgtm, approved, size/S

#474 feat: add clang-tools in tiflash ci image
  dockerfiles/ci/jenkins/tiflash/Dockerfile
Labels: lgtm, approved, size/XS

#475 docs(dockerfiles/products): add product image download counts
  dockerfiles/products/README.md
Labels: approved, size/S

#476 feat: add missing xz tool in tiflash ci image
  dockerfiles/ci/jenkins/tiflash/Dockerfile
Labels: lgtm, approved, size/S

#478 feat(ci/jenkins): add more tools to ci jenkins image
  dockerfiles/ci/base/Dockerfile
  dockerfiles/ci/jenkins/Dockerfile
Labels: lgtm, approved, size/M
