Repository PingCAP-QE/artifacts, pull requests merged in 2025-07, with the labels that each got.

#644 feat(workflows/ci): add change detection jobs for CI and release workflows
  .github/workflows/pull-ci-runtime-images.yaml
  .github/workflows/release-ci-runtime-images.yaml
  dockerfiles/ci/skaffold.yaml
Labels: lgtm, approved, size/L

#640 fix(packages): Remove QA registry destinations from image_copy_rules
  packages/delivery.yaml
Labels: approved, size/M

#648 chore(workflow): Update CI workflow to use arc-runner-set-pingcap-qe for image publishing
  .github/workflows/release-ci-runtime-images.yaml
Labels: lgtm, approved, size/XS

#649 Revert "chore(workflow): Update CI workflow to use arc-runner-set-pingcap-qe for image publishing"
  .github/workflows/release-ci-runtime-images.yaml
Labels: lgtm, approved, size/XS

#647 feat: add builder image for tici component
  .github/workflows/pull-cd-builder-images-centos7.yaml
  .github/workflows/pull-cd-builder-images.yaml
  .github/workflows/pull-cd-builder-msb.yaml
  .github/workflows/release-cd-builder-images-centos7.yaml
  .github/workflows/release-cd-builder-images.yaml
  .gitignore
  Justfile
  dockerfiles/Justfile
  dockerfiles/cd/README.md
  dockerfiles/cd/builders/tici/centos7/Dockerfile
  dockerfiles/cd/builders/tici/skaffold.centos7.non-root.yaml
  dockerfiles/cd/builders/tici/skaffold.centos7.yaml
Labels: approved, size/L

#652 rename prestop-hook to prestop-checker
  packages/delivery.yaml
Labels: lgtm, approved, size/XS

#655 fix(tici): update builder image for tici and remove devtoolset source step
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#658 fix(tici): fix packaging config and dockerfile
  dockerfiles/products/tici/Dockerfile
  packages/packages.yaml.tmpl
Labels: approved, size/S

#656 tici: set up RUSTFLAGS in image
  dockerfiles/cd/builders/tici/centos7/Dockerfile
  dockerfiles/ci/tici/Dockerfile
Labels: lgtm, approved, size/S

#661 chore(tici): update builder image tag
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#663 fix(tici): fix builder image
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#667 feat(packages): delivery images built on trunk branches to gcr.io
  packages/delivery.yaml
Labels: approved, size/XS
