Repository PingCAP-QE/artifacts, pull requests merged in 2025-08, with the labels that each got.

#671 feat(packages): deliver nextgen release branch artifacts
  packages/delivery.yaml
Labels: approved, size/XS

#672 fix(packages): deliver trunk branch enterprise images to GCR.io for `pingcap/tidb` repo
  packages/delivery.yaml
Labels: approved, size/S

#675 feat(packages): add tiup component packaging and artifact definitions
  dockerfiles/cd/builders/tiflash/centos7/Dockerfile
  packages/packages.yaml.tmpl
Labels: approved, size/M

#684 feat(dockerfiles/bases): add pingcap user and group to base Dockerfile
  dockerfiles/bases/pingcap-base/Dockerfile
  dockerfiles/bases/skaffold.yaml
Labels: approved, size/XS

#685 chore(dockerfiles/bases/tikv-base): bump base image and tag to v1.10.0
  dockerfiles/bases/skaffold.yaml
  dockerfiles/bases/tikv-base/fips.Dockerfile
Labels: approved, size/XS

#683 feat(dockerfiles/products): add multi-stage Dockerfiles with root and non-root targets
  dockerfiles/products/ng-monitoring/Dockerfile
  dockerfiles/products/pd/Dockerfile
  dockerfiles/products/ticdc/Dockerfile
  dockerfiles/products/tici/Dockerfile
  dockerfiles/products/tidb-dashboard/Dockerfile
  dockerfiles/products/tidb-tools/Dockerfile
  dockerfiles/products/tidb/br.Dockerfile
  dockerfiles/products/tidb/dumpling.Dockerfile
  dockerfiles/products/tidb/tidb-lightning.Dockerfile
  dockerfiles/products/tidb/tidb.Dockerfile
  dockerfiles/products/tidb/tidb.enterprise.Dockerfile
  dockerfiles/products/tiflash/Dockerfile
  dockerfiles/products/tiflow/dm.Dockerfile
  dockerfiles/products/tiflow/sync-diff-inspector.Dockerfile
  dockerfiles/products/tiflow/ticdc.Dockerfile
  dockerfiles/products/tikv/Dockerfile
  dockerfiles/products/tikv/fips.Dockerfile
  dockerfiles/products/tikv/next-gen.Dockerfile
  dockerfiles/products/tiproxy/Dockerfile
Labels: approved, size/L

#704 feat(packages/scripts): add support for multi-arch result file in build script
  packages/scripts/build-package-images.sh.tmpl
Labels: approved, size/S

#706 tici: static link libc++
  dockerfiles/cd/builders/tici/centos7/Dockerfile
Labels: lgtm, approved, size/S

#705 refactor(packages/scripts): refactor image result file handling and multi-arch tagging
  packages/scripts/build-package-images.sh.tmpl
Labels: approved, size/M
