Repository PingCAP-QE/artifacts, pull requests merged in 2025-03, with the labels that each got.

#568 fix(packages): remove failpoint targets for tiflash v6.1 version series
  packages/packages.yaml.tmpl
Labels: approved, size/L

#573 fix: sync new ticdc image since v9.0.0-beta
  packages/delivery.yaml
Labels: lgtm, approved, size/S

#574 fix: sync new ticdc image since v9.0.0-beta in ga
  packages/delivery.yaml
Labels: lgtm, approved, size/S

#575 feat(cd/builders): add Go 1.24 and remove older Go versions
  .github/workflows/pull-cd-builder-images-centos7.yaml
  .github/workflows/pull-cd-builder-images.yaml
  .github/workflows/release-cd-builder-images-centos7.yaml
  .github/workflows/release-cd-builder-images.yaml
  dockerfiles/cd/builders/ng-monitoring/skaffold-centos7.yaml
  dockerfiles/cd/builders/ng-monitoring/skaffold.yaml
  dockerfiles/cd/builders/pd/skaffold-centos7.yaml
  dockerfiles/cd/builders/pd/skaffold.yaml
  dockerfiles/cd/builders/tem/skaffold.yaml
  dockerfiles/cd/builders/ticdc/skaffold-centos7.yaml
  dockerfiles/cd/builders/ticdc/skaffold.yaml
  dockerfiles/cd/builders/tidb-dashboard/skaffold-centos7.yaml
  dockerfiles/cd/builders/tidb-dashboard/skaffold.yaml
  dockerfiles/cd/builders/tidb-operator/skaffold.yaml
  dockerfiles/cd/builders/tidb/skaffold-centos7.yaml
  dockerfiles/cd/builders/tidb/skaffold.yaml
  dockerfiles/cd/builders/tidbx/skaffold-centos7.yaml
  dockerfiles/cd/builders/tiflow/skaffold-centos7.yaml
  dockerfiles/cd/builders/tiflow/skaffold.yaml
Labels: approved, size/XL

#565 feat(dockerfiles/cd/builders/tikv): add perl cpans in centos7 builder
  dockerfiles/cd/builders/tikv/centos7/Dockerfile
Labels: approved, size/XS

#576 fix(packages): fix image delivery
  packages/delivery.yaml
  packages/scripts/gen-delivery-image-commands.ts
Labels: lgtm, approved, size/S

#577 Push tidb-operator-v2-prestop-hook to GAR
  packages/delivery.yaml
Labels: lgtm, approved, size/S

#579 fix(packages/scripts): add signal handlers for graceful cleanup on termination
  packages/scripts/build-in-darwin-boskos.ts
Labels: approved, size/XXL

#578 feat(packages): update ga regex patterns to include beta tags
  packages/delivery.yaml
Labels: lgtm, approved, size/M
