Repository PingCAP-QE/artifacts, pull requests merged in 2025-02, with the labels that each got.

#550 fix(ci): add concurrency limit for matrix
  .github/workflows/pull-cd-builder-images-centos7.yaml
  .github/workflows/pull-cd-builder-images.yaml
  .github/workflows/release-cd-builder-images-centos7.yaml
  .github/workflows/release-cd-builder-images.yaml
Labels: approved, size/XS

#551 ci: limit run concurrency of cd builder image
  .github/workflows/pull-cd-builder-images-centos7.yaml
  .github/workflows/pull-cd-builder-images.yaml
  .github/workflows/release-cd-builder-images-centos7.yaml
  .github/workflows/release-cd-builder-images.yaml
Labels: approved, size/XS

#548 refactor(pingcap/tiflow,pingcap/tidb-tools): refactor the building of sync-diff-inspector tool
  .github/scripts/ci.sh
  dockerfiles/products/tiflow/sync-diff-inspector.Dockerfile
  packages/README.md
  packages/delivery.yaml
  packages/offline-packages.yaml.tmpl
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/XL

#556 fix(tiflash): fix failpoint profile for history release branches
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#557 Configure backup-manager image for operator-v2
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/XS

#558 fix(tidb-operator): fix repo of `tidb-backup-manager`
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#559 Push tidb-backup-manager v2 only to GCR for now
  packages/delivery.yaml
Labels: lgtm, approved, size/XS

#560 feat(tidbx): add dockerfile
  .github/workflows/pull-cd-builder-images-centos7.yaml
  .github/workflows/release-cd-builder-images-centos7.yaml
  dockerfiles/cd/builders/tidbx/centos7/Dockerfile
  dockerfiles/cd/builders/tidbx/skaffold-centos7.yaml
Labels: approved, size/M

#563 revert(packages): revert the changes on offline packages about sync_diff_inspector tool for history versions
  packages/offline-packages.yaml.tmpl
Labels: approved, size/M
