Repository PingCAP-QE/artifacts, pull requests merged in 2025-05, with the labels that each got.

#610 chore(packages): update TiDB builder image to v2024.10.8-129-ga6c42c5
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#615 feat(ci/tici/dockerfiles): add tici Dockerfile and update skaffold configuration
  .github/workflows/pull-ci-runtime-images.yaml
  .github/workflows/release-ci-runtime-images.yaml
  dockerfiles/ci/skaffold.yaml
  dockerfiles/ci/tici/Dockerfile
Labels: lgtm, approved, size/L

#608 feature(dockerfiles/cd/builders): add non-root user support to builder images
  .github/workflows/pull-cd-builder-images-centos7.yaml
  .github/workflows/pull-cd-builder-images.yaml
  .github/workflows/pull-cd-util-images.yaml
  .github/workflows/pull-ci-runtime-images.yaml
  .github/workflows/pull-prod-runtime-images.yaml
  .github/workflows/release-cd-builder-images-centos7.yaml
  .github/workflows/release-cd-builder-images.yaml
  .github/workflows/release-cd-util-images.yaml
  .github/workflows/release-ci-runtime-images.yaml
  .github/workflows/release-prod-runtime-images.yaml
  .github/workflows/weekly-release.yaml
  dockerfiles/bases/tiflow-base/release-6.5.Dockerfile
  dockerfiles/cd/builders/ng-monitoring/Dockerfile
  dockerfiles/cd/builders/ng-monitoring/centos7/Dockerfile
  dockerfiles/cd/builders/ng-monitoring/skaffold.centos7.non-root.yaml
  dockerfiles/cd/builders/ng-monitoring/skaffold.centos7.yaml
  dockerfiles/cd/builders/ng-monitoring/skaffold.non-root.yaml
  dockerfiles/cd/builders/pd/Dockerfile
  dockerfiles/cd/builders/pd/centos7/Dockerfile
  dockerfiles/cd/builders/pd/skaffold.centos7.non-root.yaml
  dockerfiles/cd/builders/pd/skaffold.centos7.yaml
  dockerfiles/cd/builders/pd/skaffold.non-root.yaml
  dockerfiles/cd/builders/tem/Dockerfile
  dockerfiles/cd/builders/tem/skaffold.non-root.yaml
  dockerfiles/cd/builders/ticdc/Dockerfile
  dockerfiles/cd/builders/ticdc/centos7/Dockerfile
  dockerfiles/cd/builders/ticdc/skaffold.centos7.non-root.yaml
  dockerfiles/cd/builders/ticdc/skaffold.centos7.yaml
  dockerfiles/cd/builders/ticdc/skaffold.non-root.yaml
  dockerfiles/cd/builders/tidb-dashboard/Dockerfile
  dockerfiles/cd/builders/tidb-dashboard/centos7/Dockerfile
  dockerfiles/cd/builders/tidb-dashboard/skaffold.centos7.non-root.yaml
  dockerfiles/cd/builders/tidb-dashboard/skaffold.centos7.yaml
  dockerfiles/cd/builders/tidb-dashboard/skaffold.non-root.yaml
  dockerfiles/cd/builders/tidb-operator/Dockerfile
  dockerfiles/cd/builders/tidb-operator/skaffold.non-root.yaml
  dockerfiles/cd/builders/tidb/Dockerfile
  dockerfiles/cd/builders/tidb/centos7/Dockerfile
  dockerfiles/cd/builders/tidb/skaffold.centos7.non-root.yaml
  dockerfiles/cd/builders/tidb/skaffold.centos7.yaml
  dockerfiles/cd/builders/tidb/skaffold.non-root.yaml
  dockerfiles/cd/builders/tidbx/centos7/Dockerfile
  dockerfiles/cd/builders/tidbx/skaffold.centos7.non-root.yaml
  dockerfiles/cd/builders/tidbx/skaffold.centos7.yaml
  dockerfiles/cd/builders/tiflash/Dockerfile
  dockerfiles/cd/builders/tiflash/centos7/Dockerfile
  dockerfiles/cd/builders/tiflash/skaffold.centos7.non-root.yaml
  dockerfiles/cd/builders/tiflash/skaffold.centos7.yaml
  dockerfiles/cd/builders/tiflash/skaffold.non-root.yaml
  dockerfiles/cd/builders/tiflow/Dockerfile
  dockerfiles/cd/builders/tiflow/centos7/Dockerfile
  dockerfiles/cd/builders/tiflow/skaffold.centos7.non-root.yaml
  dockerfiles/cd/builders/tiflow/skaffold.centos7.yaml
  dockerfiles/cd/builders/tiflow/skaffold.non-root.yaml
  dockerfiles/cd/builders/tikv/Dockerfile
  dockerfiles/cd/builders/tikv/centos7/Dockerfile
  dockerfiles/cd/builders/tikv/fips.Dockerfile
  dockerfiles/cd/builders/tikv/skaffold.centos7.non-root.yaml
  dockerfiles/cd/builders/tikv/skaffold.centos7.yaml
  dockerfiles/cd/builders/tikv/skaffold.non-root.yaml
Labels: approved, size/XXL

#616 tici: fix release build
  packages/packages.yaml.tmpl
Labels: lgtm, approved, size/XS

#622 feat(package): update TiKV builder images and add experiment profile to routers
  packages/packages.yaml.tmpl
Labels: approved, size/S

#623 package: update dockerfile of tici
  dockerfiles/ci/tici/Dockerfile
Labels: lgtm, approved, size/XS

#628 feat(packages): enable next-gen flag in Linux build script for tiflash
  packages/packages.yaml.tmpl
Labels: approved, size/XS

#629 feat(packages): add next-gen build and artifacts for PD v9.0.0 and above
  packages/packages.yaml.tmpl
Labels: approved, size/M
